# Generated by Django 2.2.4 on 2020-02-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifthapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('M.C.A', 'M.C.A'), ('M.B.A', 'M.B.A'), ('C.S.E', 'C.S.E'), ('E.E.E', 'E.E.E'), ('E.C.E', 'E.C.E'), ('IT', 'IT'), ('CIVL', 'CIVL')], max_length=5),
        ),
    ]
